### ISSUE TITLE
Ergänzungsvorschlag Herbert (Lösungen Wiss. Grundlagen)

### ISSUE THREAD

**Issue by Bia-Ka** [FOM-ifes/VL-Vorlesungsfolien#1]
Hallo zusammen,

soeben hat Herbert an Andrea und mich folgende Bitte geschickt:

> Liebe Andrea, liebe Bianca, 
Ihr seid meine Modulleiter in diversen Statistik-Vorlesungen.
Ich möchte diese Veränderungen an 3 Modulseiten im Orientierungsskript vorschlagen, die bei meinen Studis dazu geführt haben, dass ihnen schlagartig klar wurde, was gemeint war.
Herzliche Grüße, alles Gute für das Sommersemester!
Herbert

Was meint der Rest dazu?

Viel
[Statistik-Ergänzungsvorschlag.pdf](https://github.com/FOM-ifes/VL-Vorlesungsfolien/files/6100985/Statistik-Erganzungsvorschlag.pdf)
e Grüße
Bianca

**Comment by luebby** [comment]
Finde ich klasse!

**Comment by Bia-Ka** [comment]
Auch @Schankin-A fande es gut - ich habe direkt geändert. :-)

**Comment by luebby** [comment]
Ich glaube (?) noch ist das https://github.com/luebby/Vorlesungen das aktuelle (und hier kein Fork), daher pushe ich es auch noch dort.

**Comment by NMarkgraf** [comment]
Lustig! - Ich habe gerade WM & EF gelesen, genau diese Folien und habe fast alles, was Herbert da geschrieben hat, genauso gerade in meinem Skript von Hand eingefügt. - In sofern. Vollkommen richtig, dass dort einzubauen.

**Comment by Bia-Ka** [comment]
Oh Pardon – du hast Recht. Vielleicht sollten wir aktuell noch unter luebby einarbeiten und dann einigen wir uns auf Zeitpunkt X des Umzugs. Ich glaube, so waren wir auch verblieben und ich habe mich hier schlicht vertan. ☹
Danke fürs Glattziehen.

Von: Karsten Luebke <notifications@github.com>
Gesendet: Montag, 8. März 2021 15:31
An: FOM-ifes/VL-Vorlesungsfolien <VL-Vorlesungsfolien@noreply.github.com>
Cc: Krol Prof. Dr. Bianca <bianca.krol@fom.de>; State change <state_change@noreply.github.com>
Betreff: Re: [FOM-ifes/VL-Vorlesungsfolien] Ergänzungsvorschlag Herbert (Lösungen Wiss. Grundlagen) (#1)


Ich glaube (?) noch ist das https://github.com/luebby/Vorlesungen<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_luebby_Vorlesungen&d=DwMCaQ&c=AeKhaOqF0LQ13hhQiA2Dtpl5AKKNogr-MmkOnCd0X8I&r=WJj_pE0S1n_BQA52ARo803mOdBvUC6gaHL4J2YvgXHY&m=WkaX6wuOVzZISdYtvNrof3mTwtMHYaYiMnd8X83mmnQ&s=r-eSHg8G8MsuJ_FjOK-O9_vhDh4dpgQUBM7ukjsLpc8&e=> das aktuelle (und hier kein Fork), daher pushe ich es auch noch dort.

**Comment by Bia-Ka** [comment]
Herbert an eine weitere Anregung:

> Liebe Andrea, liebe Bianca, 
und noch ein Vorschlag: die anhängende Folie zur Verteilungsfunktion kommt etwas „zusammenhangslos“ vor den Lagemaßen.
Ich fände Sie nach dem Median besser platziert, dann könnte man auch gleich pdata und qdata zusammen behandeln.

[Verteilungsfunktion vor Quantile (Median).pdf](https://github.com/FOM-ifes/VL-Vorlesungsfolien/files/6197049/Verteilungsfunktion.vor.Quantile.Median.pdf)

Was meint ROSA dazu? 

Viele Grüße
Bianca

**Comment by luebby** [comment]
Gefühlt finde ich sie da richtig wo sie ist - als Überleitung von Abbildungen von Verteilungen in die Kennzahlen von Verteilungen, bin aber leidenschaftslos.

**Comment by NMarkgraf** [comment]
Ich bin da leidenschaftlicher, ich habe so oder so immer meine Probleme mit der Folie. Egal ob ich sie da oder später einsetze. -- Mir fehlt da irgendwie die Idee, wie ich sie richtig gut in Szene setzen soll.

**Comment by luebby** [comment]
- Inhalt: Bisher hatten wir Abbildungen, jetzt wollen wir aus den Daten auch Zahlen berechnen
- Wenn es der Inhalt nicht hergibt, mach doch eine Show: "So, jetzt haben wir schon so-und-so viele Stunden das Fach gehabt - und noch keine echte Formel. Das geht gar nicht..."

- Alternativ: Wir basteln noch eine Folie wo wir zeigen wie aus einem Histogramm eine Verteilungsfunktion wird. Finde ich aber übertrieben.

**Comment by Bia-Ka** [comment]
Hallo zusammen, 

ich finde die Ideen von dir, @luebby , dazu sehr gut. Ich gehe auch immer über den Weg "bisher Abbildungen, jetzt kommen die Zahlen dazu". Das ist ja auch vorher so aufgebaut im Kapitel. So passt die Folie auch aus meiner Sicht an diese Stelle. 
Ich glaube, Herbert argumentiert hier vielleicht (nur?) über den Median oder so ähnlich und damit wählt er einen anderen Zugang und es würde eine andere Stelle besser passen. Aber dann kann er sich die Folie ja auch einfach dahin verschieben. ;-)

Also, erst einmal so lassen, würde ich sagen. @NMarkgraf , helfen dir die Ideen von Karsten weiter?

Viele Grüße 
Bianca

**Comment by Schankin-A** [comment]
Hallo,

ich habe da jetzt auch eine Weile drüber nachgegrübelt. An der Stelle passt sie schon, aber ich brauche sie ein zweites Mal, wenn ich bei qdata bin. Daher kann ich Herberts Argument nachvollziehen, würde sie aber auch an der Stelle erstmal lassen.

**Comment by NMarkgraf** [comment]
Hallo Alle,
hallo @Bia-Ka,

ehrlich gesagt: Nein. - Das liegt aber daran, dass ich nach einem Grund suche warum die Leute das überhaupt brauchen. Ich suche also nach einem erklärbaren Motiv für diese Folie. Ein "nehmt es hin und lernt es" ist mir da zu wenig. 

Gruß
Norman

**Comment by luebby** [comment]
Damit wir die Frage beantworten können: und, wie viele Rechnungen sind jetzt unter/über 10$

**Comment by NMarkgraf** [comment]
Mag sein, aber ich bin ehrlich, für mich erschliesst sich das nicht umgehend, wenn ich als Studierender da "so" drauf gucke... aber ich hadere da schon sehr lange mit. - Mir fällt das immer dann auf, wenn ich deutlich mehr Anwendungen sehe, weil ich weiß wofür ich das später gebrauchen kann, als genau in dem Moment wo ich so eine Definition erkläre...
(Die Frage, wieso ich genau das wissen will,  -- hier also wie viele Rechnungen über/unter 10$ sind -- bleibt ja auch noch, aber die kann man ggf. gut einführen ...)

**Comment by luebby** [comment]
> Die Frage, wieso ich genau das wissen will, -- hier also wie viele Rechnungen über/unter 10$ sind

Z.B. um die Kosten zu planen wenn sich das Restaurant entschließen sollte, jedem ab 10$ einen Schnaps anzubieten.

**Comment by NMarkgraf** [comment]
Oh ja, die Haare tuen da schon weh. ;-)

Ich bleibe dabei, ist mir zu wenig "story telling" an der Stelle. - Ist aber eher _mein_ Problem für die Ton-Spur und weniger eines für das Skript ...

**Comment by Bia-Ka** [comment]
Dann schließe ich jetzt hier mal mutig dieses Issue, da es ja um die Reihenfolge im Skript ging. Wenn das eine doofe Entscheidung ist, einfach wieder öffnen. :-)
