### ISSUE TITLE
Fehlermeldung beim Kompilieren: "./pandoc-filter/typography.py: createProcess: runInteractiveProcess: exec: permission denied (Permission denied)"

### ISSUE THREAD

**Issue by sebastiansauer** [FOM-ifes/VL-Vorlesungsfolien#2]
Gerade wollte ich "Kausalanalyse.Rmd" knittern,

da kam folgende Fehlermeldung:

````
./pandoc-filter/typography.py: createProcess: runInteractiveProcess: exec: permission denied (Permission denied)
Error: pandoc document conversion failed with error 83
````

Ich habe im Verzeichnis  pandoc-filter alle Dateien auf executable gesetzt: `chmod a+x *.py` und insbesondere `chmod a+x typography.py`.

[Hier](https://textuploader.com/18n5n) liegt meine SessionInfo (so gut es ging, da die Knit-Datei nicht durchlief).

**Comment by NMarkgraf** [comment]
Oh je, da fällt mir spontan nichts zu ein. :-(

**Comment by sebastiansauer** [comment]
Im neuen Repo ist es eine andere Fehlermeldung, daher schließe ich diese hier.

**Comment by NMarkgraf** [comment]
Äh, das hier ist das neue Repository...
