### ISSUE TITLE
Fehler in if (is.na(a)) return(-1L)

### ISSUE THREAD

**Issue by Bia-Ka** [FOM-ifes/VL-Vorlesungsfolien#3]
Hallo zusammen,
hat jemand eine schnelle Idee, warum ich die o. a. Fehlermeldung erhalte, wenn ich unsere Vorlesungsfolien knitr möchte? 

`Fehler in if (is.na(a)) return(-1L) : Bedingung hat Länge > 1
Ruft auf: <Anonymous> ... initPrelud -> checkPackages -> releaseCompare -> compareVersion
Ausführung angehalten`

bezieht sich in unterschiedlichen Rmds (Wissenschaftliche-Methodik, Wiederholung-Quiz, Anhang Inferenz immer auf unsere ersten R Chunk 

```
{r setup, include=FALSE}
# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    "WM-",         # Prefix für Terminlisten etc.
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)
```

Viele Grüße
Bianca

**Comment by NMarkgraf** [comment]
Ja, weil diese Folien seit zwei Jahren nicht gewartet werden, weil Karsten (@luebby) und ich (@NMarkgraf) keinen gemeinsamen Termin finden um das aktuelle Repository aus dem Private-Bereich hierhin zu migrieren. Der Fehler ist bekannt und im privaten Repository auch schon gefixed.
